### ISSUE TITLE
二级选项的时候 可以针对二级的设置选择数量吗？

### ISSUE THREAD

**Issue by DuQuanzhong** [windows7lake/ll_dropdown_menu#1]
二级选项的时候 可以针对二级的设置选择数量吗？
<img width="241" alt="截屏2024-01-05 14 57 19" src="https://github.com/windows7lake/ll_dropdown_menu/assets/5549754/937f05a0-6f2d-46e0-9dfa-0ba4bebd103f">

**Comment by windows7lake** [comment]
demo中有示例，DropDownCascadeList中的maxMultiChoiceSize可设置多选数量
