### ISSUE TITLE
可以配置DropDownItem 选中后(highlight)状态下的Icon吗?

### ISSUE THREAD

**Issue by liuhll** [windows7lake/ll_dropdown_menu#3]
例如给`DropDownItem`加一个参数用于显示当下拉选菜单被选中后的`icon`的图标，目前是当被选中后，icon就没有了
```
DropDownItem({
    this.text,
    this.icon,
    this.activeIcon,
    this.data,
    this.check = false,
  });
```

**Comment by windows7lake** [comment]
@liuhll 目前是有该功能的，能上传一下视频或者截图说明一下具体问题吗？
<img width="481" alt="image" src="https://github.com/windows7lake/ll_dropdown_menu/assets/10578898/b63f73d0-4bdc-4ce1-8d12-c0151ef57b55">
<img width="433" alt="image" src="https://github.com/windows7lake/ll_dropdown_menu/assets/10578898/58dcaae7-a99b-4424-808e-34c7ae37ff64">

**Comment by liuhll** [comment]
我看到了 谢谢， 通过DropDownHeader组件的DropDownItemStyle可以设置，这样也可以！我之前想的是通过DropDownItem来设置

**Comment by wiscgazf** [comment]
你还可以设置高亮和 高亮下的文本 可以通过 DropDownController设置

![Uploading image.png…]()

**Comment by wiscgazf** [comment]
也可以通过 dropDownController.headerStatus 设置高亮和高亮的自定的文本内容
`
DropDownViewWrapper(
                      height: 185.h,
                      child: _GradePane(
                        grade: _gradeId,
                        onTapHandle: (el) {
                          dropDownController.headerStatus[dropDownController.headerIndex] =
                              DropDownHeaderStatus(text: el, highlight: _gradeId.isNotEmpty);
                          setState(() {
                            _gradeId = el;
                          });
                        },
                      ),
                    )
`
