### ISSUE TITLE
怎么设置菜单展开的初始值？似乎没有找到可以设置的位置

### ISSUE THREAD

**Issue by zhanchen18** [windows7lake/ll_dropdown_menu#5]
![image](https://github.com/user-attachments/assets/f960ad0c-e356-47dc-a84c-2f25e9ff6f94)
这里的代码限制死了只能第一项选中，我尝试在生成items时就修改选中状态，并不能解决问题

**Comment by windows7lake** [comment]
@zhanchen18 我找时间调整一下，或者你提交一个pr

**Comment by zhanchen18** [comment]
![image](https://github.com/user-attachments/assets/2a08236d-17cc-4602-bc56-a67274a9f14f)

我尝试了这样解决，似乎在效果上是可行的，不知道这样是否正确？

**Comment by windows7lake** [comment]
@zhanchen18 可行
