### ISSUE TITLE
打开下拉框选择后，已选择项在下拉框里显示

### ISSUE THREAD

**Issue by bobqiu** [windows7lake/ll_dropdown_menu#6]
看到其它插件的样例图，此插件能达到同样的效果吗，应该如何操作呢，谢谢
<img width="467" alt="image" src="https://github.com/user-attachments/assets/63dac1fe-f1c8-4545-ae77-eaba1c36812c">

**Comment by windows7lake** [comment]
@bobqiu 可以实现，不过DropDownView（下拉视图）需要按照你当前的业务，去自定义下拉视图

**Comment by bobqiu** [comment]
如何操作呢，在example里好像没有类似的例子

**Comment by windows7lake** [comment]
@bobqiu 查看 [Demo5](https://github.com/windows7lake/ll_dropdown_menu/blob/main/example/lib/drop_down_demo5.dart)
